apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-info-reflective
  labels:
    app: system-info-reflective
spec:
  selector:
    matchLabels:
      app: system-info-reflective
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: system-info-reflective
    spec:
      containers:
        - name: system-info-reflective
          image: xuujie/system-info-reflective:latest
          env:
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: com.mysql.jdbc.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/sysinfo
            - name: SPRING_JPA_DATABASE-PLATFORM
              value: org.hibernate.dialect.MySQL5Dialect
            - name: SPRING_JPA_HIBERNATE_NAMING_PHYSICAL-STRATEGY
              value: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: system-info-reflective-service
spec:
  selector:
    app: system-info-reflective
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
